SEED = 42

EXPECTED_COLUMNS = {
    "date",
    "item_id",
    "category",
    "price",
    "cost",
    "sales",
    "promo_active",
    "competitor_price",
    "ad_spend",
    "stock_level",
    "weather_index",
}

CATEGORICAL_FEATURES = ["item_id", "category"]

MODEL_FEATURES = [
    "item_id",
    "category",
    "price",
    "cost",
    "promo_active",
    "competitor_price",
    "ad_spend",
    "stock_level",
    "weather_index",
    "lag_1_clean",
    "lag_2_clean",
    "lag_3_clean",
    "lag_7_clean",
    "lag_14_clean",
    "lag_21_clean",
    "lag_28_clean",
    "roll_mean_7_clean",
    "roll_mean_30_clean",
    "roll_std_30_clean",
    "roll_median_7_clean",
    "roll_median_30_clean",
    "ewm_mean_7_clean",
    "ewm_mean_30_clean",
    "same_weekday_mean_4",
    "short_trend",
    "lag_week_ratio",
    "item_promo_mean",
    "price_cost_ratio",
    "price_competitor_ratio",
    "price_vs_regular_90",
    "log_ad_spend",
    "month",
    "day_of_week",
    "is_weekend",
    "day_of_year_sin",
    "day_of_year_cos",
]

FEATURE_GROUPS = {
    "identity": ["item_id", "category"],
    "price": ["price", "cost", "price_cost_ratio", "price_competitor_ratio"],
    "promotion": ["promo_active", "ad_spend", "log_ad_spend"],
    "competition": ["competitor_price"],
    "availability": ["stock_level"],
    "history": [
        "lag_1_clean",
        "lag_2_clean",
        "lag_3_clean",
        "lag_7_clean",
        "lag_14_clean",
        "lag_21_clean",
        "lag_28_clean",
        "roll_mean_7_clean",
        "roll_mean_30_clean",
        "roll_std_30_clean",
        "roll_median_7_clean",
        "roll_median_30_clean",
        "ewm_mean_7_clean",
        "ewm_mean_30_clean",
        "same_weekday_mean_4",
        "short_trend",
        "lag_week_ratio",
        "item_promo_mean",
    ],
    "calendar_external": [
        "weather_index",
        "month",
        "day_of_week",
        "is_weekend",
        "day_of_year_sin",
        "day_of_year_cos",
    ],
}
